import { CountryCodes } from ".";
import IFile from "./IFile";
import IVehicleDamage from "./IVehicleDamage";
import IVehicleEquipmentData from "./IVehicleEquipmentData";
import IVehicleEquipmentHighlightData from "./IVehicleEquipmentHighlightData";
import IVehicleImages from "./IVehicleImages";
import IVehiclePaintState from "./IVehiclePaintState";
import IVehicleTireSet from "./IVehicleTireSet";

export default interface IVehicle {
  vin: string;
  make: string;
  makeInternalDatReference?: string;
  model: string;
  ez: string;
  mileageInKm: number;
  category: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
  transmission: 0 | 1;
  upholstery: 0 | 1 | 2 | 3;
  numSeats: number;
  fuelType: 0 | 1 | 2 | 3 | 4 | 5;
  doors: 0 | 1 | 2;
  engineSizeInCcm: number;
  enginePowerInHp: number;
  color: string;
  bodyColorCode: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;
  dimensionWidthInCm: number;
  dimensionHeightInCm: number;
  dimensionLengthInCm: number;
  unloadedWeightInKg: number;
  lastHu: string;
  huReportExists: boolean;
  numPreOwners: number;
  numKeys: number;
  vatIdReportable: boolean;
  fullServiceHistory: boolean;
  isServiceHistoryAvailable: boolean;
  isReimportedVehicle: boolean;
  euroNorm: string;
  hadAccident: boolean;
  accidentDescription: string;
  hasDamages: boolean;
  damagesDescription: string;
  damages: IVehicleDamage;
  additionalDamages: string;
  additionalInfo: string;
  isReadyToDrive: boolean;
  readyToDrive: 0 | 1 | 2;
  readyToDriveDetails: string;
  imageUrls?: IVehicleImages;
  vehicleImages: IVehicleImages;
  attachments: IFile;
  urlToAttachment1: string;
  urlToAttachment2: string;
  urlToAttachment3: string;
  urlToVehicleSummarySheet: string;
  estimatedValue: number;
  basedOnInternalVehicleExpertReport: boolean;
  lastServiceInspectionDate: string;
  lastServiceInspectionMileage: number;
  isCocDocumentAvailable: boolean;
  countryOfLastRegistration: CountryCodes;
  origin: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
  dataSource: number;
  isCreatedFromVehicleReport: boolean;
  paintState: IVehiclePaintState;
  tires: IVehicleTireSet;
  id: number;
  ac: number;
  navigation: number;
  headlights: number;
  coupling: number;
  vehicleHeater: number;
  parkingAssistance: number;
  sunRoof: number;
  sportPackage: number;
  seriesEquipments: string[];
  specialEquipments: string[];
  equipmentData: IVehicleEquipmentData;
  equipmentHighlights: IVehicleEquipmentHighlightData;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
  uuid: string;
}
